# Fifa RAW data Transformation

Steps 
- Importing Libraries
- Importing data
- EDAAAAAAAAAAAAAAAA

In [34]:
#Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import seaborn as srn
import math
import random
import datetime
warnings.filterwarnings('ignore')

In [35]:
df = pd.read_csv('fifa21_raw_data.csv')
df.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   

   POT                         Club  ...     A/W     D/W   IR PAC SHO  PAS  \
0   93         \n\n\n\nFC Barcelona  ...  Medium     Low  5 ★  85  92   91   
1   92             \n\n\n\nJuventus  ...    High     Low  5 ★  89  93   81   
2   93      \n\n\n\nAtlético Madrid  ...  Medium  Medium  3 ★  87  92   78   
3   91      \n\n\n\nManchester City  ...    High    High  4 ★  76  86   93   
4   91  \n\n\n\nParis Saint-Germain  ...    High  Medium  5 ★  91  85   86   

  DRI DEF PHY Hits  
0  95  38  65  771  
1  89  35  77  562  
2  90  52  90  150  
3  88  64  78  207  
4  94  36  59  595  

[5 rows x 77 columns]

In [36]:
df.shape

(18979, 77)

In [4]:
df.isna().sum()

ID              0
Name            0
LongName        0
photoUrl        0
playerUrl       0
             ... 
PAS             0
DRI             0
DEF             0
PHY             0
Hits         2595
Length: 77, dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                18979 non-null  int64 
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64 
 7   ↓OVA              18979 non-null  int64 
 8   POT               18979 non-null  int64 
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64 
 16  Best Position     18979 non-null  object
 17  Joined      

In [7]:
df[['ID','Name','LongName']]

ID               Name                      LongName
0      158023           L. Messi                  Lionel Messi
1       20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro
2      200389           J. Oblak                     Jan Oblak
3      192985       K. De Bruyne               Kevin De Bruyne
4      190871          Neymar Jr    Neymar da Silva Santos Jr.
...       ...                ...                           ...
18974  247223             Xia Ao                        Ao Xia
18975  258760           B. Hough                     Ben Hough
18976  252757        R. McKinley                Ronan McKinley
18977  243790       Wang Zhen'ao                  Zhen'ao Wang
18978  252520          Zhou Xiao                     Xiao Zhou

[18979 rows x 3 columns]

In [8]:
df[['↓OVA','POT','Club']]

↓OVA  POT                         Club
0        93   93         \n\n\n\nFC Barcelona
1        92   92             \n\n\n\nJuventus
2        91   93      \n\n\n\nAtlético Madrid
3        91   91      \n\n\n\nManchester City
4        91   91  \n\n\n\nParis Saint-Germain
...     ...  ...                          ...
18974    47   55           \n\n\n\nWuhan Zall
18975    47   67      \n\n\n\nOldham Athletic
18976    47   65           \n\n\n\nDerry City
18977    47   57     \n\n\n\nDalian YiFang FC
18978    47   57     \n\n\n\nDalian YiFang FC

[18979 rows x 3 columns]

We observe there are too many new line characters and those have to be deleted.

In [9]:

for i in df['Club'].unique():
    try:
        df['Club'].replace(i,i.replace('\n',''),inplace = True)
    except:
        pass
   

In [10]:
df['Club'].head()

0           FC Barcelona
1               Juventus
2        Atlético Madrid
3        Manchester City
4    Paris Saint-Germain
Name: Club, dtype: object

In [11]:
df[['Contract','Positions']]

Contract   Positions
0      2004 ~ 2021  RW, ST, CF
1      2018 ~ 2022      ST, LW
2      2014 ~ 2023          GK
3      2015 ~ 2023     CAM, CM
4      2017 ~ 2022     LW, CAM
...            ...         ...
18974  2018 ~ 2022          CB
18975  2020 ~ 2021          CM
18976  2019 ~ 2020          CM
18977  2020 ~ 2022          RW
18978  2019 ~ 2023      CB, LB

[18979 rows x 2 columns]

In [12]:
for i in df['Contract'].unique():
    try:
        df['Contract'].replace(i,i.replace('~','-'),inplace = True)
    except:
        pass
df['Contract'].head()  


0    2004 - 2021
1    2018 - 2022
2    2014 - 2023
3    2015 - 2023
4    2017 - 2022
Name: Contract, dtype: object

In [13]:
df[['Height','Weight','Preferred Foot']]

Height Weight Preferred Foot
0      170cm   72kg           Left
1      187cm   83kg          Right
2      188cm   87kg          Right
3      181cm   70kg          Right
4      175cm   68kg          Right
...      ...    ...            ...
18974  178cm   66kg          Right
18975  175cm   65kg          Right
18976  179cm   74kg          Right
18977  175cm   69kg          Right
18978  188cm   75kg           Left

[18979 rows x 3 columns]

In [14]:
df["Height"].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [15]:
def height(x):
    k = x.replace('\'','.').replace('"','').split('.')
    centi = round((float(k[0])*12*2.54) + (float(k[1])*2.54),2)
    return centi

for i in df['Height'].unique():     
        try:
            df['Height'].replace(i,i.replace('cm',''),inplace = True)
            df['Height'].replace(i,height(i), inplace = True)
        except:
            pass

In [16]:
df["Height"].unique()

array(['170', '187', '188', '181', '175', '184', '191', '178', '193',
       '185', '199', '173', '168', '176', '177', '183', '180', '189',
       '179', '195', '172', '182', '186', '192', '165', '194', '167',
       '196', '163', '190', '174', '169', '171', '197', '200', '166',
       187.96, '164', '198', 190.5, 195.58, 180.34, 193.04, 185.42,
       182.88, 177.8, 175.26, 167.64, 170.18, 162.56, '201', '158', '162',
       '161', '160', '203', '157', '156', '202', '159', '206', '155'],
      dtype=object)

In [17]:
df['Height'] = pd.to_numeric(df['Height']) 
df['Height'].dtype

dtype('float64')

In [18]:
df["Weight"].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [19]:
def weight(x):
    if x[3:6]=='lbs':
        k = x.replace('lbs','.').split('.')
        kg = round(float(k[0])*0.45,1)
    else:
        pass
    return kg

for i in df['Weight'].unique():     
        try:
            df['Weight'].replace(i,i.replace('kg',''),inplace = True)
            df['Weight'].replace(i,weight(i), inplace = True)
        except:
            pass

In [20]:
df["Weight"].unique()

array(['72', '83', '87', '70', '68', '80', '71', '91', '73', '85', '92',
       '69', '84', '96', '81', '82', '75', '86', '89', '74', '76', '64',
       '78', '90', '66', '60', '94', '79', '67', '65', '59', '61', '93',
       '88', '97', '77', '62', '63', '95', '100', '58', 82.4, 80.5, 77.4,
       88.2, 79.2, 83.2, 76.5, 91.4, 75.6, 72.5, 65.7, 58.5, 85.5, 78.3,
       66.6, 74.2, 71.5, 86.4, 81.5, 62.6, 69.3, 70.7, 73.4, '98', '103',
       '99', '102', '56', '101', '57', '55', '104', '107', '110', '53',
       '50', '54', '52'], dtype=object)

In [21]:
df['Weight'] = pd.to_numeric(df['Weight']) 
df['Weight'].dtype

dtype('float64')

In [22]:
df[['BOV','Best Position']]

BOV Best Position
0       93            RW
1       92            ST
2       91            GK
3       91           CAM
4       91            LW
...    ...           ...
18974   49            CB
18975   51           CAM
18976   49           CAM
18977   48            ST
18978   50            LB

[18979 rows x 2 columns]

In [23]:
df[['Joined','Loan Date End']]

Joined Loan Date End
0       Jul 1, 2004           NaN
1      Jul 10, 2018           NaN
2      Jul 16, 2014           NaN
3      Aug 30, 2015           NaN
4       Aug 3, 2017           NaN
...             ...           ...
18974  Jul 13, 2018           NaN
18975   Aug 1, 2020           NaN
18976   Mar 8, 2019           NaN
18977  Sep 22, 2020           NaN
18978  Jul 29, 2019           NaN

[18979 rows x 2 columns]

In [24]:
df['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

We should change the dates from words to actual dates

In [25]:
for i in list(df['Joined'].unique()):
    try:
        xx = datetime.datetime.strptime(i,'%b %d, %Y').strftime('%d/%m/%Y')
        f = '%d/%m/%Y'
        df['Joined'].replace(i,datetime.datetime.strptime(xx,f),inplace=True)
    except:
        pass


In [26]:
df['Joined'].head()

0   2004-07-01
1   2018-07-10
2   2014-07-16
3   2015-08-30
4   2017-08-03
Name: Joined, dtype: datetime64[ns]

In [27]:
for j in list(df['Loan Date End'].unique()):
    try:
        xx1 = datetime.datetime.strptime(j,'%b %d, %Y').strftime('%d/%m/%Y')
        f1 = '%d/%m/%Y'
        df['Loan Date End'].replace(j,datetime.datetime.strptime(xx1,f1),inplace=True)
    except:
        pass

In [28]:
df['Loan Date End'].unique()

array([                          'NaT', '2021-06-30T00:00:00.000000000',
       '2020-12-31T00:00:00.000000000', '2021-01-30T00:00:00.000000000',
       '2022-06-30T00:00:00.000000000', '2021-05-31T00:00:00.000000000',
       '2021-07-05T00:00:00.000000000', '2021-12-31T00:00:00.000000000',
       '2021-07-01T00:00:00.000000000', '2021-01-01T00:00:00.000000000',
       '2021-08-31T00:00:00.000000000', '2021-01-31T00:00:00.000000000',
       '2021-12-30T00:00:00.000000000', '2021-06-23T00:00:00.000000000',
       '2021-01-03T00:00:00.000000000', '2021-11-27T00:00:00.000000000',
       '2021-01-17T00:00:00.000000000', '2023-06-30T00:00:00.000000000',
       '2021-07-31T00:00:00.000000000', '2020-11-22T00:00:00.000000000',
       '2022-05-31T00:00:00.000000000', '2020-12-30T00:00:00.000000000',
       '2021-01-04T00:00:00.000000000', '2020-11-30T00:00:00.000000000',
       '2021-08-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [29]:
df[['Value','Wage','Release Clause']]

Value   Wage Release Clause
0      €103.5M  €560K        €138.4M
1         €63M  €220K         €75.9M
2        €120M  €125K        €159.4M
3        €129M  €370K          €161M
4        €132M  €270K        €166.5M
...        ...    ...            ...
18974    €100K    €1K           €70K
18975    €130K   €500          €165K
18976    €120K   €500          €131K
18977    €100K    €2K           €88K
18978    €100K    €1K           €79K

[18979 rows x 3 columns]

In [39]:
def call(value):
    value = value.replace('€','')
    value = value.replace('K','000')
    value = value.replace('M','000000')
    value = value.replace('.','F')
    if  'F' in value:
        value = value.replace('F','')
        value = value = int(value) / 10
    vale = int(value)
    return vale
       

In [43]:
for i in df['Value']:
    try:
        df['Value'].replace(i,height(i), inplace = True)
    except:
        pass
df['Value'].unique()

array([103500000,  63000000, 120000000, 129000000, 132000000, 111000000,
       120500000, 102000000, 185500000, 110000000, 113000000,  90500000,
        82000000,  17500000,  83500000,  33500000, 114500000,  78000000,
       103000000, 109000000,  92000000,  10000000,  76500000,  89500000,
        87500000,  79500000, 124000000, 114000000,  95000000,  92500000,
       105500000,  88500000,  85000000,  81500000,  26000000,  21000000,
        56000000,  67500000,  53000000,  36500000,  51000000,  65500000,
        46500000,  61500000,  72500000,  77500000,  43500000,  32500000,
        36000000,  32000000,  54000000,  49500000,  57000000,  66500000,
        74500000,  71500000, 121000000,  99000000,  67000000,  86500000,
        93500000,  70000000,  62000000,  66000000,  58000000,  44000000,
        81000000,  37000000,  14500000,  46000000,  47500000,  52500000,
        54500000,  34500000,  57500000,  51500000,  44500000,  55000000,
        48000000,  60500000,  63500000,  61000000, 

In [45]:
for i in df['Wage']:
    try:
        df['Wage'].replace(i,call(i), inplace = True)
    except:
        pass
df['Wage'].unique()

array([560000, 220000, 125000, 370000, 270000, 240000, 250000, 160000,
       260000, 210000, 310000, 130000, 350000, 300000, 190000, 145000,
       195000, 100000, 140000, 290000,  82000, 110000, 230000, 155000,
       200000, 165000,  95000, 170000, 105000, 115000, 150000, 135000,
        55000,  58000,  81000,  34000, 120000,  59000,  90000,  65000,
        56000,  71000,  18000,  75000,  47000,  20000,  84000,  86000,
        74000,  78000,  27000,  68000,  85000,  25000,  46000,  83000,
        54000,  79000, 175000,  43000,  49000,  45000,  38000,  41000,
        39000,  23000,  51000,  50000,  87000,  30000,  14000,  69000,
        31000,  64000,  53000,  35000,  21000,  28000,  17000,  33000,
        70000,  32000,  89000,  26000,  40000,  76000,  72000,  48000,
        36000,  29000,  60000,  16000,  37000,  24000,  52000,      0,
        62000,  73000,  63000,  19000,   1000,  66000,  80000,  12000,
         2000,  42000,  13000,    900,  57000,  77000,  61000,  22000,
      

In [46]:
for i in df['Release Clause']:
    try:
        df['Release Clause'].replace(i,call(i), inplace = True)
    except:
        pass
df['Release Clause'].unique()

array([138400000,  75900000, 159400000, ...,     59000,     35000,
           64000], dtype=int64)

In [47]:
for i in df['Hits']:
    try:
        df['Hits'].replace(i,call(i), inplace = True)
    except:
        pass
df['Hits'].unique()

array([7.71e+02, 5.62e+02, 1.50e+02, 2.07e+02, 5.95e+02, 2.48e+02,
       2.46e+02, 1.20e+02, 1.60e+03, 1.30e+02, 3.21e+02, 1.89e+02,
       1.75e+02, 9.60e+01, 1.18e+02, 2.16e+02, 2.12e+02, 1.54e+02,
       2.05e+02, 2.02e+02, 3.39e+02, 4.08e+02, 1.03e+02, 3.32e+02,
       8.60e+01, 1.73e+02, 1.61e+02, 3.96e+02, 1.10e+03, 4.33e+02,
       2.42e+02, 2.06e+02, 1.77e+02, 1.50e+03, 1.98e+02, 4.59e+02,
       1.17e+02, 1.19e+02, 2.09e+02, 8.40e+01, 1.87e+02, 1.65e+02,
       2.03e+02, 6.50e+01, 3.36e+02, 1.26e+02, 3.13e+02, 1.24e+02,
       1.45e+02, 5.38e+02, 1.82e+02, 1.01e+02, 4.50e+01, 3.77e+02,
       9.90e+01, 1.94e+02, 4.03e+02, 4.14e+02, 5.93e+02, 3.74e+02,
       2.45e+02, 3.20e+03, 2.66e+02, 2.99e+02, 3.09e+02, 2.15e+02,
       2.65e+02, 2.11e+02, 1.12e+02, 3.37e+02, 7.00e+01, 1.59e+02,
       6.88e+02, 1.16e+02, 6.30e+01, 1.44e+02, 1.23e+02, 7.10e+01,
       2.24e+02, 1.13e+02, 1.68e+02, 6.10e+01, 8.90e+01, 1.37e+02,
       2.78e+02, 7.50e+01, 1.48e+02, 1.76e+02, 1.97e+02, 2.64e

In [48]:
df['IR'].head()

0    5 ★
1    5 ★
2    3 ★
3    4 ★
4    5 ★
Name: IR, dtype: object

In [49]:
df['IR'] = df['IR'].str.replace('\W', '', regex=True)
df['IR'].head()

0    5
1    5
2    3
3    4
4    5
Name: IR, dtype: object

In [51]:
df['Hits'].dtype

dtype('float64')

In [52]:
df[['W/F','SM','A/W','D/W']]

W/F  SM     A/W     D/W
0      4 ★  4★  Medium     Low
1      4 ★  5★    High     Low
2      3 ★  1★  Medium  Medium
3      5 ★  4★    High    High
4      5 ★  5★    High  Medium
...    ...  ..     ...     ...
18974  2 ★  2★  Medium  Medium
18975  2 ★  2★  Medium  Medium
18976  2 ★  2★  Medium  Medium
18977  3 ★  2★  Medium  Medium
18978  3 ★  2★  Medium  Medium

[18979 rows x 4 columns]

In [53]:
df['W/F'] = df['W/F'].str.replace('\W', '', regex=True)
df['W/F'].head()

0    4
1    4
2    3
3    5
4    5
Name: W/F, dtype: object

In [54]:
df['SM'] = df['SM'].str.replace('\W', '', regex=True)
df['SM'].head()

0    4
1    5
2    1
3    4
4    5
Name: SM, dtype: object

In [55]:
df['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [56]:
df.describe()

ID           Age          ↓OVA           POT           BOV  \
count   18979.000000  18979.000000  18979.000000  18979.000000  18979.000000   
mean   226403.384794     25.194109     65.718636     71.136414     66.751726   
std     27141.054157      4.710520      6.968999      6.114635      6.747193   
min        41.000000     16.000000     47.000000     47.000000     48.000000   
25%    210135.000000     21.000000     61.000000     67.000000     62.000000   
50%    232418.000000     25.000000     66.000000     71.000000     67.000000   
75%    246922.500000     29.000000     70.000000     75.000000     71.000000   
max    259216.000000     53.000000     93.000000     95.000000     93.000000   

              Value           Wage  Release Clause     Attacking  \
count  1.897900e+04   18979.000000    1.897900e+04  18979.000000   
mean   2.865063e+06    9092.062279    3.962951e+06    248.938142   
std    7.685154e+06   19707.021089    9.772762e+06     74.299428   
min    0.000000e+00       0.000000    0.000000e+00     42.000000   
25%    4.750000e+05    1000.000000    4.235000e+05    222.000000   
50%    9.500000e+05    3000.000000    1.000000e+06    263.000000   
75%    2.000000e+06    8000.000000    2.800000e+06    297.000000   
max    1.855000e+08  560000.000000    2.031000e+08    437.000000   

           Crossing  ...   GK Reflexes   Total Stats    Base Stats  \
count  18979.000000  ...  18979.000000  18979.000000  18979.000000   
mean      49.688392  ...     16.519627   1595.286949    355.702197   
std       18.131153  ...     17.854079    269.874789     40.761117   
min        6.000000  ...      2.000000    747.000000    232.000000   
25%       38.000000  ...      8.000000   1452.000000    327.000000   
50%       54.000000  ...     11.000000   1627.000000    356.000000   
75%       63.000000  ...     14.000000   1781.000000    384.000000   
max       94.000000  ...     90.000000   2316.000000    498.000000   

                PAC           SHO           PAS           DRI           DEF  \
count  18979.000000  18979.000000  18979.000000  18979.000000  18979.000000   
mean      67.453975     53.457031     57.681016     62.875020     49.866221   
std       10.677859     13.827425     10.081857      9.927415     16.443213   
min       25.000000     16.000000     25.000000     25.000000     12.000000   
25%       61.000000     44.000000     51.000000     57.000000     35.000000   
50%       68.000000     56.000000     58.000000     64.000000     53.000000   
75%       75.000000     64.000000     64.000000     69.000000     63.000000   
max       96.000000     93.000000     93.000000     95.000000     91.000000   

                PHY          Hits  
count  18979.000000  16384.000000  
mean      64.368934     26.569580  
std        9.601883    128.631295  
min       28.000000      1.000000  
25%       58.000000      2.000000  
50%       65.000000      5.000000  
75%       71.000000     15.000000  
max       91.000000   8400.000000  

[8 rows x 58 columns]

In [57]:
df.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   

   POT                         Club  ...     A/W     D/W IR PAC SHO  PAS DRI  \
0   93         \n\n\n\nFC Barcelona  ...  Medium     Low  5  85  92   91  95   
1   92             \n\n\n\nJuventus  ...    High     Low  5  89  93   81  89   
2   93      \n\n\n\nAtlético Madrid  ...  Medium  Medium  3  87  92   78  90   
3   91      \n\n\n\nManchester City  ...    High    High  4  76  86   93  88   
4   91  \n\n\n\nParis Saint-Germain  ...    High  Medium  5  91  85   86  94   

  DEF PHY   Hits  
0  38  65  771.0  
1  35  77  562.0  
2  52  90  150.0  
3  64  78  207.0  
4  36  59  595.0  

[5 rows x 77 columns]

In [58]:
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']

# print columns
print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 58 numerical features : ['ID', 'Age', '↓OVA', 'POT', 'BOV', 'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats', 'Base Stats', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits']

We have 19 categorical features : ['Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Club', 'Contract', 'Positions', 'Height', 'Weight', 'Preferred Foot', 'Best Position', 'Joined', 'Loan Date End', 'W/F', 'SM', 'A/W', 'D/W', 'IR']


# Visualization